screenshots of course videos for ads2 and dnw
world-class/notes pull request #24
Opened 2022-10-31 03:58 UTC by hitfzyangdianshi

screenshots of course videos for ads2 and dnw

you can read these screenshots if you are lazy and don't want to watch videos when reviewing

2022-10-31 14:40 UTC, sglavoie requested changes
Thank you once again @hitfzyangdianshi! In the case of your other PR at https://github.com/world-class/binary-assets/pull/20, I think it made sense to share it as you did due to the archive size and our lack of ability to store it properly.

In this case, there are only two screenshots, we could easily add them to this repo so we don't have to track as many external links that might break. Would you mind if we share these directly as PNG/JPG files in this repo instead (in the same directory as the Markdown files)?

2022-10-31 17:48 UTC, hitfzyangdianshi commented
hi. I update the link. I upload the two word docx files into my own repository (https://github.com/cyberfoxmeow/my-binary-assets-for-UOL-bsccs-online-courses.git), as the commit (https://github.com/world-class/notes/pull/24/commits/0fbc96be0ef23476f3ab781ada15669695610069) shows, so no need to worry about broken external links now. 

(https://github.com/cyberfoxmeow/my-binary-assets-for-UOL-bsccs-online-courses/blob/main/ads2%20video%20screenshots/ads2%20video%20screenshots%20by%20cyberfox_meow.docx)

(https://github.com/cyberfoxmeow/my-binary-assets-for-UOL-bsccs-online-courses/blob/main/dnw%20video%20screenshots/dnw%20video%20screenshots%20by%20cyberfox_meow.docx)

2022-11-01 00:36 UTC, sglavoie commented
Hi @hitfzyangdianshi. The issue is that this content is not directly part of `world-class/notes`. Although I believe you have good intentions, the issue remains: you could change your username; make the repo private; move or rename the files; etc. Of course, this is not about a trust issue, but rather about the fact that if others want to contribute to this content, they cannot do so via this `world-class/notes` because the content lives outside of it.

If you use relative links instead and store the files in the same directory as the Markdown files, it will make it possible for everyone to retrieve these files by forking or pulling from `world-class/notes`.

Now, I guess you will be aware of all this and because these files are relatively heavy, I think it will be fine for the time being to leave them in your own repo 😄. We should eventually have a place to store this conveniently, but I understand how you could have reached your conclusion, as it makes sense. So thank you for your contributions as always!

2022-11-01 00:36 UTC, sglavoie approved these changes

2022-11-01 00:37 UTC, merged